apiVersion: v1
kind: ConfigMap
metadata:
  name: dafnegodinez-config
  labels:
    app: postgres
data:
  DEV_SECRET_KEY: hackernews-dev
  DEV_DATABASE: woizthst
  DEV_USER: woizthst
  DEV_PASSWORD: 2OvF4jzDA0TwI-qhN0AN7pl-D7MZ3zWG
  DEV_HOST: heffalump.db.elephantsql.com
  DEV_PORT: "5432"
