apiVersion: apps/v1
kind: Deployment
metadata:
  name: dafnegodinez
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dafnegodinez
  template:
    metadata:
      labels:
        app: dafnegodinez
    spec:
      containers:
      - image: okteto.dev/dafnegodinez:latest
        name: dafnegodinez
        envFrom:
        - configMapRef:
            name: dafnegodinez-config
        livenessProbe:
          httpGet:
            path: /ht/
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: dafnegodinez
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "dafnegodinez"
    port: 8080
  selector:
    app: dafnegodinez
